<> yaml 
name: Despliegue a Azure

# ¿Cuándo se ejecuta? Cuando hacemos push a la rama main
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # El Agente (Linux)

    steps:
    # 1. Bajar el código del repositorio
    - uses: actions/checkout@v2

    # 2. Iniciar sesión en Azure usando el Secreto
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
# 3. Desplegar el archivo Bicep
    - name: Desplegar Bicep
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: westeurope
        template: ./main.bicep
        deploymentName: github-deploy-01
